### ISSUE TITLE
Truck Height is being ignored in Truck Routing

### ISSUE THREAD

**Issue by mikeg55442** [microsoft/BingMapsRESTToolkit#43] opened 2020-01-02 00:38 UTC
I have tried defining various heights of Truck Trailers from a reasonable 16ft to a totally ridiculous 150ft and the same route is calculated each time over interstates and within major cities (Chicago, Cleaveland, etc.). Are there others with this issue. Am I not setting a parameter correctly? Thanks for any help.

**Comment by IoTGirl** [comment] 2020-01-29 16:57
This is being reviewed in the Forums. Please close this as a duplicate of [https://social.msdn.microsoft.com/Forums/en-US/426b4cce-82f2-4092-8ca6-cca6b0dcab96/truck-height-being-ignored-in-truck-routing-calculations?forum=bingmapsservices](https://social.msdn.microsoft.com/Forums/en-US/426b4cce-82f2-4092-8ca6-cca6b0dcab96/truck-height-being-ignored-in-truck-routing-calculations?forum=bingmapsservice)s

**Closed** 2020-01-29 17:16 UTC
