### ISSUE TITLE
Sign package assembly

### ISSUE THREAD

**Issue by BerserkerDotNet** [microsoft/BingMapsRESTToolkit#50] opened 2020-10-22 21:17 UTC
Hi, 
[BingMapsRESTToolkit.dll](https://github.com/microsoft/BingMapsRESTToolkit/blob/master/Source/BingMapsRESTToolkit.csproj#L39) is not signed. This causes issues when using it from projects that are signed. Is there a reason it is left not signed? If no, can make it signed.

Thanks.

**Comment by IoTGirl** [comment] 2021-01-29 17:03
Duplicate of https://github.com/microsoft/BingMapsRESTToolkit/issues/12

**Closed by IoTGirl** 2021-01-29 17:03 UTC

**Comment by nakhtar-ntg** [comment] 2021-11-06 22:30
Why was it closed? Any solution to signing the DLL or any other workaround? @IoTGirl
