### ISSUE TITLE
Object not set to an instance of an object

### ISSUE THREAD

**Issue by nickbnick** [microsoft/BingMapsRESTToolkit#24] opened 2018-07-19 00:05 UTC
Getting "object not set to an instance of an object" error when using RouteRequest with over 25 waypoints.  After testing it seems to be due to using RouteAttributeType.ExcludeItinerary.  Removing that type stops error. 

 StackTrace	"   at BingMapsRESTToolkit.RouteRequest.<>c__DisplayClass22_0.<MergeRoutes>b__0() in C:\\Users\\richbrun\\Desktop\\Code Samples\\GitHub\\BingMapsRESTToolkit\\Source\\Requests\\RouteRequest.cs:line 443\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()"

**Comment by rbrundritt** [comment] 2022-03-17 23:13
Closing as unable to reproduce and a lot has changed since this bug was reported.

**Closed by rbrundritt** 2022-03-17 23:13 UTC
