### ISSUE TITLE
FindTimeZoneRequest not in latest nuget package

### ISSUE THREAD

**Issue by ericholland6** [microsoft/BingMapsRESTToolkit#49] opened 2020-07-15 20:26 UTC
Unable to use FindTimeZoneRequest as it is not availalable in the latest nuget package(1.1.4). Any suggestions for getting around this?

**Comment by Remi123** [comment] 2021-01-22 14:35
I'm in the same boat. The 1.1.4 package doesn't contains LocationRecogRequest which is problematic

**Comment by jane-bolton** [comment] 2021-03-11 20:02
This looks like an identical issue to #31. When can we hope to see an update?

**Comment by rbrundritt** [comment] 2022-03-17 21:44
Closing as duplicate of #31 Note that you can easily pull this library into your solution and reference locally.

**Closed by rbrundritt** 2022-03-17 21:44 UTC
